{
 "title": "Atiic",
 "time": { "from": "2022-04-27T15:05:29.199Z", "to": "2022-04-27T18:28:16.111Z" },
 "panels": [
  {
   "title": "Measurement Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT() FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds}",
     "rawQueryText": "SELECT COUNT() FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT  spl06Temperature, aht21Temperature, ts FROM atiic\n",
     "rawQueryText": "SELECT  spl06Temperature, aht21Temperature, ts FROM atiic\n",
     "timeColumns": [ "ts" ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT aht21Humidity, ts FROM atiic",
     "rawQueryText": "SELECT aht21Humidity, ts FROM atiic",
     "timeColumns": [ "ts" ]
    }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT spl06Pressure, ts FROM atiic",
     "rawQueryText": "SELECT spl06Pressure, ts FROM atiic",
     "timeColumns": [ "ts" ]
    }
   ]
  },
  {
   "title": "TTL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT ttl FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds}",
     "rawQueryText": "SELECT ttl FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT avg(spl06Temperature), avg(aht21Temperature), max(ts) as _ts FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds} GROUP BY (1000*ts/$__interval_ms)",
     "rawQueryText": "SELECT avg(spl06Temperature), avg(aht21Temperature), max(ts) as _ts FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds} GROUP BY (1000*ts/$__interval_ms)",
     "timeColumns": [ "_ts" ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "queryText": "SELECT avg(aht21Humidity), max(ts) as _ts FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds} group by (1000*ts/$__interval_ms)",
     "rawQueryText": "SELECT avg(aht21Humidity), max(ts) as _ts FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds} group by (1000*ts/$__interval_ms)",
     "timeColumns": [ "_ts" ]
    }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT avg(spl06Pressure), max(ts) as _ts FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds} group by (1000*ts/$__interval_ms)",
     "rawQueryText": "SELECT avg(spl06Pressure), max(ts) as _ts FROM atiic WHERE ts >= ${__from:date:seconds} AND ts < ${__to:date:seconds} group by (1000*ts/$__interval_ms)",
     "timeColumns": [ "_ts" ]
    },
    {
     "queryText": "SELECT Count() FROM atiic ",
     "rawQueryText": "SELECT Count() FROM atiic ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}